# Generated by Django 5.0.4 on 2024-04-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='commentor',
        ),
    ]
